// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// NewCollectorTemplateClient is the client API for NewCollectorTemplate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewCollectorTemplateClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type newCollectorTemplateClient struct {
	cc grpc.ClientConnInterface
}

func NewNewCollectorTemplateClient(cc grpc.ClientConnInterface) NewCollectorTemplateClient {
	return &newCollectorTemplateClient{cc}
}

func (c *newCollectorTemplateClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/build_collector.v1alpha1.NewCollectorTemplate/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewCollectorTemplateServer is the server API for NewCollectorTemplate service.
// All implementations should embed UnimplementedNewCollectorTemplateServer
// for forward compatibility
type NewCollectorTemplateServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
}

// UnimplementedNewCollectorTemplateServer should be embedded to have forward compatible implementations.
type UnimplementedNewCollectorTemplateServer struct {
}

func (UnimplementedNewCollectorTemplateServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}

// UnsafeNewCollectorTemplateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewCollectorTemplateServer will
// result in compilation errors.
type UnsafeNewCollectorTemplateServer interface {
	mustEmbedUnimplementedNewCollectorTemplateServer()
}

func RegisterNewCollectorTemplateServer(s grpc.ServiceRegistrar, srv NewCollectorTemplateServer) {
	s.RegisterService(&_NewCollectorTemplate_serviceDesc, srv)
}

func _NewCollectorTemplate_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewCollectorTemplateServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/build_collector.v1alpha1.NewCollectorTemplate/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewCollectorTemplateServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NewCollectorTemplate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "build_collector.v1alpha1.NewCollectorTemplate",
	HandlerType: (*NewCollectorTemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _NewCollectorTemplate_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1alpha1/new-collector-template.proto",
}
